# -*- coding: utf-8 -*-
{
    'name': 'POS User Access Rights',
    'version': '17.0',
    'summary': """Disable POS access based on the User, Disable POS Features like Payment, Quantity,
     Discount, Edit Price, Remove Orderline, Manual Customer Selection and Plus and Minus qty,
     POS User Permissions Access Control for Point of Sale User Roles in POS Security Settings for POS,
     Role-Based POS Access Point of Sale Authorization User Privileges for POS Access Rights Configuration Role-Based POS Restrictions,
     POS User Access Management POS User Security Permission Levels in Point of Sale,POS Disable Buttons, POS Access Rights, POS Buttons Access,
     Allow/Disable payments, Allow/Disable add product, All In One POS Access Management, Allow/Disable delete, Allow/Disable price, Allow/Disable discount,
     Allow/Disable quantity, Control access to the POS payments,POS Disable Refund Button, Control access to the POS quantity, Control access to the POS delete,
     This apps helps you to Allow/Disable POS Features like Discount, Change Price, Payment, Quantity, Remove Orderline | Allow/Disable pos features,
     Restriction of POS User | POS Access Rules | Point of Sale Access Rights | Allow/Disable POS Features Point of Sales Access rightsControl access to the POS price, Control access to the POS add product
     POS User Role Assignment Secure POS Access Customizable Access Controls for POS POS Extra Access Rights,
     Restrict Access Point Of Sale POS Disable Customer Button POS Deny Numpad POS Restrict Plus-Minus Buttons,
     POS Disable Quantity Button POS Discount Disable POS Payment Button Disable POS Disable Price POS Access Rights Odoo.""",
    'description': """Enable/Disable POS functions based on the User.""",
    'category': 'Point of Sale',
    "author": "Khaled Hassan",
    'website': "https://apps.odoo.com/apps/modules/browse?search=Khaled+hassan",
    'depends': ['base', 'mail', 'point_of_sale', 'account', 'sale_management', 'pos_discount'],
    'data': [
        'views/res_users_views.xml',
        'views/return_products.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'pos_user_disable_buttons/static/src/js/refund_button.js',
            'pos_user_disable_buttons/static/src/js/action_pad.js',
            'pos_user_disable_buttons/static/src/js/numpad.js',
            'pos_user_disable_buttons/static/src/js/payment_screen.js',
            'pos_user_disable_buttons/static/src/js/ticket_screen.js',
            'pos_user_disable_buttons/static/src/xml/refund_button.xml',
            'pos_user_disable_buttons/static/src/xml/action_pad.xml',
            'pos_user_disable_buttons/static/src/xml/numpad.xml',
            'pos_user_disable_buttons/static/src/xml/payment_screen.xml',
            'pos_user_disable_buttons/static/src/xml/ticket_screen.xml',
            'pos_user_disable_buttons/static/src/xml/discount_button.xml',
        ],
    },
    "images": ['static/description/main_screenshot.png'],
    'currency': 'EUR',
    'price': '15',
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': True,
}
