# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'NHCL Customizations',
    'version': '1.0',
    'sequence': 1,
    'category': 'Purchase',
    "author": "New Horizons Cybersoft Ltd",
    "website": "https://www.nhclindia.com/",
    'summary': 'Purchase,Contact,Stock,Product Customizations',
    'description': """
This module contains all the common features of Transport and Check.
    """,
    'depends': ['purchase', 'base', 'stock', 'mail', 'base_setup', 'product', 'point_of_sale', 'hr',
                'purchase_product_matrix', 'sale',
                'purchase_stock', 'sale_stock', 'hr_expense', 'fleet', 'account', 'mrp', 'loyalty',
                'stock_picking_batch', 'wt_pos_fix_discount', 'l10n_in'],
    'external_dependencies': {
        'python': ['odf', 'openpyxl', 'xlrd', 'XlsxWriter'],
    },
    'data': [
        'security/ir.model.access.csv',
        'security/sales_incentive_security.xml',
        'security/stock_backorder_notify_security.xml',
        'data/sequence.xml',
        'data/active_promo_cron.xml',
        'data/stock_backorder_cron.xml',
        "data/stock_picking_inherit.xml",
        'views/ho_store_configuration_view.xml',
        'views/transport_menu.xml',
        'views/pos_dashboard_menu.xml',
        'views/transport_details_view.xml',
        'views/fleet_vehicle_view.xml',
        'views/routes_details_view.xml',
        'views/location_view.xml',
        'views/transport_entry_view.xml',
        'wizard/mis_reports_actions_menu.xml',
        # 'report/dev_transport_report_template.xml',
        # 'report/dev_transport_report_menu.xml',
        # 'report/delivery_slip.xml',
        'views/contact_master.xml',
        "views/purchase_approval_buttons.xml",
        "views/sale_order_view.xml",
        "views/account_move.xml",
        'views/product_template_views.xml',
        'views/stock_views.xml',
        'views/loyalty_program_view.xml',
        'views/stock_batch_views.xml',
        'views/store_target_data_view.xml',
        'views/store_target_data_report_view.xml',
        'views/loyalty_view.xml',
        'views/hr_employee_view.xml',
        'views/res_config_settings_view.xml',
        'views/import_move_lines_view.xml',
        'views/setu_sales_incentive_structure_views.xml',
        'views/setu_sales_incentive_structure_line_views.xml',
        'views/cv_ir_cron_history.xml',
        'views/ir_cron_views.xml',
        'views/login_template.xml',
        'views/cash_register_views.xml',
        'views/live_sync_views.xml',
        'views/cf_inventory_count_views.xml',
        'views/master_sequence_views.xml',
        'views/matching_material_view.xml',
        'report/store_target_report_template_view.xml',
        'report/setu_sales_person_incentive_detailed_report.xml',
        'report/setu_sales_person_incentive_summary_report.xml',
        'report/barcode_sheet_delivery.xml',
        'report/allow_slip.xml',
        'report/credit_note_pos.xml',
        'report/transfer_note.xml',
        'report/new_otd_report.xml',
        'report/account_transfer_out.xml',
        'report/pdf_sale_person_report.xml',
        'wizard/pos_exchange_popup.xml',
        'wizard/import_order_lines_view.xml',
        'views/last_scanned_serial_number.xml',
        'wizard/purchase_pt_upload_views.xml',
        'views/inventory_movement_report_views.xml',
        'wizard/inventory_movement_report_wizard_views.xml',
        'wizard/serial_no_confirm_popup.xml',
        'wizard/import_stock_receipt_wizard.xml',
        'wizard/credit_note_settlement_summary_report.xml',
        'report/hired_products_report.xml',
        'report/hired_products_template.xml',
        'wizard/pos_daily_sale_report.xml',
        'wizard/nhcl_pos_delivery_order_quantity_wise_report.xml',
        'wizard/nhcl_site_wise_sale_report.xml',
        'wizard/nhcl_credit_note_bills_summary_report.xml',
        'wizard/nhcl_store_asset_wise_report.xml',
        'wizard/nhcl_bill_wise_sale_report.xml',
        'wizard/nhcl_hsn_with_tax_wise_report.xml',
        'wizard/nhcl_pos_cancelled_bills_summary_report.xml',
        'wizard/mode_of_payment_report_view.xml',
        'wizard/nhcl_tax_wise_report_view.xml',
        'wizard/nhcl_lfb_report_view.xml',
        'wizard/nhcl_daily_sale_detailed_report.xml',
        'wizard/nhcl_terminal_wise_mop_report.xml',
        'wizard/sale_person_report.xml',
        'report/mode_of_payment_report.xml',
        'report/tax_wise_report.xml',
        'report/nhcl_lfb_report.xml',
        'wizard/delivery_import_wizard_view.xml',
        'views/stock_location_views.xml',
        'views/barcode_scanner_view.xml',
        'wizard/receipt_backdate_wizard_view.xml',

        'wizard/allow_slip_wizard.xml',
        'wizard/nhcl_customer_credit_note_report.xml',
        'report/mm_allow_slip.xml',
        #'views/stock_upload_views.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'nhcl_customizations/static/src/scss/list_sticky_header.scss',
            'nhcl_customizations/static/src/scss/live_sync.scss',
            'nhcl_customizations/static/src/js/multiselect.js',
            'nhcl_customizations/static/src/js/pos_dashboard.js',
            'nhcl_customizations/static/src/js/qty_stock.js',
            'nhcl_customizations/static/src/js/patch_list_width_render.js',
            'nhcl_customizations/static/src/xml/pos_dashboard.xml',
            'nhcl_customizations/static/src/xml/qty_stock.xml',
            # 'nhcl_customizations/static/src/xml/live_sync.xml',
            'nhcl_customizations/static/src/css/style.css',
            'nhcl_customizations/static/src/css/qty_stock.css',
            # 'nhcl_customizations/static/src/js/live_sync.js',
            'nhcl_customizations/static/src/js/favicon.js',
            'nhcl_customizations/static/src/fields/one2manysearch/one2manysearch_template.xml',
            'nhcl_customizations/static/src/fields/one2manysearch/one2manysearch.js',
            'nhcl_customizations/static/src/js/empty_page.js',
            'nhcl_customizations/static/src/xml/empty_page.xml',
        ],
        'point_of_sale._assets_pos': [
            'nhcl_customizations/static/src/xml/pos_highlight.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
